Varied heroes hw3
Orangehundred/basic-flixel-project pull request #2
Opened 2022-02-23 23:30 UTC by Orangehundred

2022-02-24 04:58 UTC, SamBumgardner requested changes
Nice work! 

There's one hard requirement that needs to be fixed before we're done, which is that the controllable hero should only move if its corresponding arrow keys are pressed. 

There are a variety of other comments with suggestions you could consider implementing too, but they won't be required to be finished with the assignment.

You finished bonuses for collision with walls, and the "bounce off of walls" behavior is in the same vein as the "screen wrap bonus", so you'll have extra points for both of those. Let me know when you've pushed new commit(s) to fix things up and I'll re-review it ASAP.

2022-02-24 04:58 UTC, SamBumgardner commented on source/ControllableHero.hx
> +                }
We're currently missing the last part of the controllable hero's requirements:
> It should stop moving if no arrow keys are pressed.

This also has the potentially undesirable side effect of having a sort of "priority order" of movement directions. If both left and right are pressed at the same time, the player ends up going to the right. This isn't something that needs to  change to complete the assignment, but it might be worth doing.

There are bunch of ways you can change this to make the hero only move if the relevant keys are pressed, let me know if you'd like to talk it over.

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +            }
This doesn't really belong inside your `changeColor()` function, probably would be best to move it to its own thing that's called within `update()`

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +            }
Also, nice logic for making it bounce off of the edges of the screen, it's a pretty fun effect!

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +                this.velocity.y *= 1;
Worth noting that because this is positive `1`, this line really isn't doing anything. If you want blocks to bounce off of the Y boundaries, you'll want to use `-1` like you did earlier.

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +            else if (this.velocity.y < 0 && this.x <= 0)
Had an x instead of y here.
```suggestion
            else if (this.velocity.y < 0 && this.y <= 0)
```

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +                this.velocity.y *= 1;
Also applies to the other y-related block below.

2022-02-24 04:58 UTC, SamBumgardner commented on source/ScreensaverHero.hx
> +            if (x < y)
I'm guessing this was meant to be an else if
```suggestion
            else if (x < y)
```

2022-02-24 04:58 UTC, SamBumgardner commented on source/Main.hx
> +		addChild(new FlxGame(650, 450, PlayState));
these values should be 640, 480 if you want to match the size of your window. 

The window dimensions are actually determined by a line in the repo's `project.xml`, the numbers here determine the sort of space the internal screen tries to take up - if this number doesn't match the window dimensions, then it ends up scaling in a weird way.

2022-02-24 04:58 UTC, SamBumgardner commented on source/PlayState.hx
>  	}
I was wondering why your `ScreensaverHero` objects were colliding with the walls, even though it looked like only Controlled hero should be checked for collision.

It turns out that it's happening because if `null` is passed into `FlxG.collide()`, it's treated as "collide with everything else that's been added to the `FlxState`.  

your `controlledHero` variable is actually `null` inside of `update()` (you can use `trace()` to display its value if you'd like to double check), which is why everything's getting collided against your `Wall` objects.

But why was `controlledHero` null? It's because inside create you have the line
```
var controlledHero = ...
```
having the var keyword in front means it's creating a new local variable `controlledHero`, instead of using the instance variable you declared earlier. 

Just changing it to
```
controlledHero = new ControllableHero(...);
```
should fix the null problem, and collision will actually be working the way that it appears it should.

2022-02-24 04:58 UTC, SamBumgardner commented on source/PlayState.hx
>  	}
The "when the first thing is null, just collide with everything" behavior isn't very well documented, but you can see it inside the source code here: https://github.com/HaxeFlixel/flixel/blob/master/flixel/FlxG.hx#L412-L413

2022-02-24 06:07 UTC, Orangehundred commented on source/PlayState.hx
>  	}
Yea I noticed I had that unintended side effect of the screensaver objects colliding with the walls and couldn't understand it. It felt nice to have some unintended thing turn out good for once.

2022-02-24 18:27 UTC, SamBumgardner requested changes
Got some of the movement thing fixed, but not completely. See the comment for details.

Nice work with the other changes 👍

2022-02-24 18:27 UTC, SamBumgardner commented on source/ControllableHero.hx
> +            }
It's good that holding opposite directions cancels out velocity appropriately, but we still have the problem that after tapping a direction the hero will continue to move forever. We want the character to stop if no directional keys are pressed.

You could add another conditional to check directions aren't pressed, but it'd be even easier to just set the x & y velocity to 0 before checking for inputs. If nothing ends up being pressed, the character just doesn't move.

2022-02-25 00:23 UTC, Orangehundred commented on source/ControllableHero.hx
> +            }
If I do an else statement and set velocity.x and velocity,y to 0, the controlledHero won't move at all. How do I do something like "if not"?

2022-02-25 00:37 UTC, Orangehundred commented on source/ControllableHero.hx
> +            }
Nevermind, I now understood what you meant and have implemented the changes.

2022-02-25 00:40 UTC, SamBumgardner approved these changes
Looks good, you can merge when ready.

2022-02-25 00:40 UTC, merged